dropbox_access_token = "sl.BzYzYbqGc4L9SzOuRgtCJz7R7mRGkWDfgO8hK__BFIlLpPDe1QvTu1Qci3u17V0Jzglp9gC_lf5lKvJ11dZ2w0ewyqAVuO1bGVUxOx86uvq4X1aTw2jIkHf_b50xYtLraaDHPUDJzS9b3Bh9cqUmbfg"
supabase_url = "https://wrkdqkildspebpcpwdse.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indya2Rxa2lsZHNwZWJwY3B3ZHNlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxMjg1MjA1NiwiZXhwIjoyMDI4NDI4MDU2fQ.DFy7BvWY__V6uaNKeclmghCbz4XYRn62oYWwJnTMN-M"

app_key = "h81jix8rba56dhi"
app_secret = "07pcnboj2pb2pdu"
dropbox_refresh_token = "b8UgESKwge0AAAAAAAAAASY-QNUmJ52D02TfXEnM8nGCljfWE7kKtna-XoyIhZ7Q"